services:
  postgres:
    image: 'postgres:latest'
    hostname: 'postgres'
    environment:
      POSTGRES_DB: vetclinic
      POSTGRES_PASSWORD: vetsecret
      POSTGRES_USER: vetuser
      PGUSER: vetuser
    ports:
      - '5432:5432'
  vetclinic:
    volumes:
      - "./:/vetclinic"
    image: 'vetclinic'
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    command: sh -c "/wait && mvn spring-boot:run"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30